using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;
using IkeaEeg.Core;
using IkeaEeg.Data;
using IkeaEeg.Experiment;
using IkeaEeg.Neuro;

namespace IkeaEeg.Dashboard
{
    /// <summary>
    /// Publishes a snapshot of runtime status to a JSON file for the researcher dashboard.
    ///
    /// STRICTLY OBSERVATIONAL, AND STRUCTURALLY SO. This component holds no reference it can
    /// write through: every field it touches is read from a public getter that already existed
    /// for the Console and the self test. It calls nothing on the experiment, subscribes to no
    /// event that could reorder a frame, and has no method that returns a value to anything in
    /// the project. Deleting this file changes no recorded data and no participant experience.
    ///
    /// EDITOR ONLY. The bootstrap below is compiled out of a player build, so a Quest session
    /// never creates this object, never opens this file and never spends a millisecond here.
    /// The researcher runs the experiment from the Editor over Quest Link, which is exactly
    /// where the dashboard is useful.
    ///
    /// The file is written to a FIXED path, not into the session folder: the dashboard has to
    /// be able to find it before a session exists, and between sessions.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class ResearcherStatusWriter : MonoBehaviour
    {
        public const string FolderName = "IKEA_EEG_Dashboard";
        public const string FileName = "status.json";

        /// <summary>
        /// Stamped into every snapshot. The dashboard refuses to present a payload that does not
        /// say LIVE, so a mock file cannot be displayed as though it came from hardware.
        /// </summary>
        public const string DataSourceLive = "LIVE";

        [Tooltip("Seconds between snapshots. Four a second is smooth to read and costs nothing.")]
        [SerializeField] float m_IntervalSeconds = 0.25f;

        EventLogger m_Logger;
        ExperimentManager m_Manager;
        AuraLslReceiver m_Receiver;
        EegFeaturePipeline m_Pipeline;
        ShadowModeController m_Shadow;
        ShadowDecisionSink m_Sink;

        string m_Path;
        float m_NextWrite;
        string m_ElapsedForSession = string.Empty;
        float m_SessionStartedAt;

#if UNITY_EDITOR
        /// <summary>
        /// Creates the writer without touching the scene.
        ///
        /// The experiment scene is code-generated by a DESTRUCTIVE builder, so adding a
        /// component to it would mean running that builder. Spawning the object at runtime
        /// instead leaves the authored scene byte-identical and keeps this entirely outside
        /// the experiment's own object graph.
        /// </summary>
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        static void Bootstrap()
        {
            if (FindAnyObjectByType<ResearcherStatusWriter>() != null)
                return;

            var host = new GameObject("IKEA_EEG Researcher Status (editor only)");
            host.AddComponent<ResearcherStatusWriter>();
            DontDestroyOnLoad(host);
        }
#endif

        void Awake()
        {
            var folder = Path.Combine(Application.persistentDataPath, FolderName);

            try
            {
                Directory.CreateDirectory(folder);
                m_Path = Path.Combine(folder, FileName);
            }
            catch (IOException e)
            {
                Debug.LogWarning("[IKEA_EEG] Researcher status file unavailable: " + e.Message);
                enabled = false;
                return;
            }

            Debug.Log("[IKEA_EEG] Researcher status: " + m_Path);
        }

        void Update()
        {
            if (Time.realtimeSinceStartup < m_NextWrite)
                return;

            m_NextWrite = Time.realtimeSinceStartup + Mathf.Max(0.05f, m_IntervalSeconds);

            Rebind();
            WriteSnapshot();
        }

        /// <summary>
        /// Re-finds the components each tick when one is missing. Cheap, and it means the
        /// dashboard starts reporting the moment a scene load brings the pipeline into
        /// existence, rather than staying blank until the next play session.
        /// </summary>
        void Rebind()
        {
            if (m_Logger == null) m_Logger = FindAnyObjectByType<EventLogger>();
            if (m_Manager == null) m_Manager = FindAnyObjectByType<ExperimentManager>();
            if (m_Receiver == null) m_Receiver = FindAnyObjectByType<AuraLslReceiver>();
            if (m_Pipeline == null) m_Pipeline = FindAnyObjectByType<EegFeaturePipeline>();
            if (m_Shadow == null) m_Shadow = FindAnyObjectByType<ShadowModeController>();
            if (m_Sink == null) m_Sink = FindAnyObjectByType<ShadowDecisionSink>();
        }

        void WriteSnapshot()
        {
            var sessionId = m_Logger != null ? m_Logger.sessionId : string.Empty;

            if (sessionId != m_ElapsedForSession)
            {
                m_ElapsedForSession = sessionId;
                m_SessionStartedAt = Time.realtimeSinceStartup;
            }

            var elapsed = string.IsNullOrEmpty(sessionId)
                ? 0d
                : Time.realtimeSinceStartup - m_SessionStartedAt;

            var json = new StringBuilder(4096);

            json.Append('{');
            Str(json, "data_source", DataSourceLive);
            Str(json, "written_utc", System.DateTime.UtcNow.ToString("o", Inv));
            Num(json, "unity_time", Time.realtimeSinceStartupAsDouble);

            AppendSession(json, sessionId, elapsed);
            AppendAcquisition(json);
            AppendChannels(json);
            AppendWindow(json);
            AppendShadow(json);

            TrimComma(json);
            json.Append('}');

            WriteAtomic(json.ToString());
        }

        void AppendSession(StringBuilder json, string sessionId, double elapsed)
        {
            json.Append("\"session\":{");
            Str(json, "session_id", sessionId);
            Str(json, "experiment_session_id",
                m_Logger != null ? m_Logger.experimentSessionId : string.Empty);
            Num(json, "run_index", m_Logger != null ? m_Logger.runIndex : 0);
            Bool(json, "active", m_Logger != null && m_Logger.sessionActive);
            Str(json, "phase", m_Manager != null
                ? m_Manager.state.ToString()
                : m_Logger != null ? m_Logger.currentState : "Unknown");
            Str(json, "room", m_Logger != null ? m_Logger.currentRoom : string.Empty);
            Str(json, "directory", m_Logger != null ? m_Logger.sessionDirectory : string.Empty);
            Str(json, "root_folder", m_Logger != null ? m_Logger.rootFolderName : string.Empty);
            Num(json, "elapsed_seconds", elapsed);
            TrimComma(json);
            json.Append("},");
        }

        void AppendAcquisition(StringBuilder json)
        {
            json.Append("\"acquisition\":{");
            Str(json, "stream_name", AuraLslReceiver.StreamName);
            Bool(json, "connected", m_Receiver != null && m_Receiver.isConnected);
            Str(json, "detail", m_Receiver != null ? m_Receiver.detail : "no receiver in scene");
            Num(json, "samples_received", m_Receiver != null ? m_Receiver.samplesReceived : 0L);

            // StreamMetadata is a struct: read it through the receiver or not at all.
            Num(json, "nominal_srate", m_Receiver != null ? m_Receiver.metadata.nominalSrate : 0d);
            Num(json, "stream_channels", m_Receiver != null ? m_Receiver.metadata.channelCount : 0);

            Num(json, "time_correction", m_Receiver != null ? m_Receiver.timeCorrection : 0d);
            Num(json, "windows_published", m_Pipeline != null ? m_Pipeline.windowsPublished : 0L);
            TrimComma(json);
            json.Append("},");
        }

        /// <summary>
        /// Per-electrode health, by LABEL, so the dashboard never has to know channel order.
        ///
        /// Three states only, and "unknown" is a real answer: before the first window nothing
        /// is known about any electrode, and showing that honestly is better than showing
        /// eight reassuring green rows.
        /// </summary>
        void AppendChannels(StringBuilder json)
        {
            json.Append("\"channels\":[");

            var features = m_Pipeline != null ? m_Pipeline.latest : null;
            var montage = m_Pipeline != null ? m_Pipeline.montage : null;

            if (montage != null)
            {
                for (var c = 0; c < montage.channels.Count; c++)
                {
                    var label = montage.LabelOfIndex(c);
                    var state = "unknown";

                    if (features != null && features.channelCount > 0)
                    {
                        state = "healthy";

                        var degraded = features.degradedChannels;

                        if (degraded != null)
                        {
                            for (var i = 0; i < degraded.Length; i++)
                            {
                                if (degraded[i] != c)
                                    continue;

                                state = "degraded";
                                break;
                            }
                        }
                    }

                    json.Append('{');
                    Num(json, "index", c + 1);
                    Str(json, "label", label);
                    Str(json, "state", state);
                    Str(json, "rois", RoiNamesFor(montage, c));
                    TrimComma(json);
                    json.Append("},");
                }
            }

            TrimComma(json);
            json.Append("],");
        }

        static string RoiNamesFor(AuraMontageConfig montage, int channel)
        {
            var names = new StringBuilder();

            foreach (var roi in montage.regions)
            {
                var indices = montage.ResolveRoi(roi.roiName, out _);

                if (indices == null)
                    continue;

                foreach (var index in indices)
                {
                    if (index != channel)
                        continue;

                    if (names.Length > 0)
                        names.Append(", ");

                    names.Append(roi.roiName);
                    break;
                }
            }

            return names.ToString();
        }

        void AppendWindow(StringBuilder json)
        {
            json.Append("\"window\":{");

            var f = m_Pipeline != null ? m_Pipeline.latest : null;

            Bool(json, "present", f != null);

            if (f != null)
            {
                Num(json, "sample_count", f.sampleCount);
                Num(json, "channel_count", f.channelCount);
                Num(json, "lsl_start", f.windowStart);
                Num(json, "lsl_end", f.windowEnd);
                Num(json, "theta_fc", f.frontalTheta);
                Num(json, "alpha_post", f.posteriorAlpha);
                Bool(json, "feature_validity", f.featureValidity);
                Bool(json, "roi_valid", f.roiValid);
                Bool(json, "fc_roi_valid", f.frontalThetaValid);
                Bool(json, "post_roi_valid", f.posteriorAlphaValid);
                Bool(json, "filter_settled", f.filterSettled);
                Bool(json, "window_complete", f.windowComplete);
                Bool(json, "spectral_valid", f.spectralValid);
                Bool(json, "channel_checks", f.channelChecksPassed);
                Bool(json, "cross_channel", f.crossChannelChecksPassed);
                Bool(json, "channel_health", f.channelHealthPassed);
                Num(json, "degraded_in_roi", f.degradedInsideRoi);
                Num(json, "degraded_outside_roi", f.degradedOutsideRoi);
                Num(json, "valid_channels",
                    f.channelCount - (f.degradedChannels?.Length ?? 0));
                Num(json, "near_identical_pairs", f.nearIdenticalPairs);
                Str(json, "near_identical_detail", f.nearIdenticalDetail);
                Str(json, "degraded_detail", f.degradedDetail);
                Str(json, "flags", f.QualityText());
                Str(json, "breakdown", f.ValidityBreakdown());
                Str(json, "power_units", f.powerUnits);
            }

            TrimComma(json);
            json.Append("},");
        }

        void AppendShadow(StringBuilder json)
        {
            json.Append("\"shadow\":{");
            Bool(json, "present", m_Shadow != null);
            Bool(json, "subscribed", m_Shadow != null && m_Shadow.isSubscribed);
            Num(json, "windows_observed", m_Shadow != null ? m_Shadow.windowsObserved : 0L);
            Num(json, "decisions_generated",
                m_Shadow != null ? m_Shadow.decisionsGenerated : 0L);
            Num(json, "rows_written", m_Sink != null ? m_Sink.rowsWritten : 0L);
            Str(json, "controller_version", ShadowModeController.ControllerVersion);
            Str(json, "montage_status", ShadowModeController.MontageStatus);

            // ShadowDecision is a readonly struct, so "have we one yet" is a counter question,
            // not a null check. Before the first decision the level is reported as
            // INDETERMINATE anyway, which is also the only value it can ever hold.
            var hasDecision = m_Shadow != null && m_Shadow.decisionsGenerated > 0;
            var decision = m_Shadow != null ? m_Shadow.lastDecision : default;

            Str(json, "level", hasDecision
                ? decision.level.ToString().ToUpperInvariant()
                : "INDETERMINATE");
            Str(json, "rejected_reason", hasDecision
                ? decision.rejectedReason.ToString()
                : string.Empty);
            Bool(json, "baseline_valid", hasDecision && decision.baselineValid);

            json.Append("\"rejections\":[");

            if (m_Shadow != null)
            {
                foreach (var pair in m_Shadow.rejectionTally)
                {
                    json.Append('{');
                    Str(json, "cause", pair.Key);
                    Num(json, "count", pair.Value);
                    TrimComma(json);
                    json.Append("},");
                }
            }

            TrimComma(json);
            json.Append("]},");
        }

        /// <summary>
        /// Writes through a temporary file and moves it into place.
        ///
        /// The dashboard polls this path several times a second. Writing in place would let it
        /// read a half-written file and show garbage; a move is atomic enough that it never
        /// sees anything but a complete snapshot.
        /// </summary>
        void WriteAtomic(string payload)
        {
            if (string.IsNullOrEmpty(m_Path))
                return;

            try
            {
                var temp = m_Path + ".tmp";
                File.WriteAllText(temp, payload);

                if (File.Exists(m_Path))
                    File.Delete(m_Path);

                File.Move(temp, m_Path);
            }
            catch (IOException)
            {
                // A dropped snapshot is invisible: the next one is 250 ms away. Never log here,
                // or a locked file would flood the Console during a run.
            }
        }

        // ---- Minimal JSON emitters -----------------------------------------------------------
        // Hand-rolled on purpose: JsonUtility cannot express the nested, partly dynamic shape
        // above, and a serializer dependency is not worth carrying for one read-only file.

        static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        static void Str(StringBuilder b, string key, string value)
        {
            b.Append('"').Append(key).Append("\":\"").Append(Escape(value)).Append("\",");
        }

        static void Num(StringBuilder b, string key, double value)
        {
            b.Append('"').Append(key).Append("\":");

            if (double.IsNaN(value) || double.IsInfinity(value))
                b.Append("null,");
            else
                b.Append(value.ToString("R", Inv)).Append(',');
        }

        static void Num(StringBuilder b, string key, long value)
        {
            b.Append('"').Append(key).Append("\":").Append(value.ToString(Inv)).Append(',');
        }

        static void Bool(StringBuilder b, string key, bool value)
        {
            b.Append('"').Append(key).Append("\":").Append(value ? "true" : "false").Append(',');
        }

        static void TrimComma(StringBuilder b)
        {
            if (b.Length > 0 && b[b.Length - 1] == ',')
                b.Length--;
        }

        static string Escape(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            var b = new StringBuilder(value.Length + 8);

            foreach (var c in value)
            {
                switch (c)
                {
                    case '"': b.Append("\\\""); break;
                    case '\\': b.Append("\\\\"); break;
                    case '\n': b.Append("\\n"); break;
                    case '\r': b.Append("\\r"); break;
                    case '\t': b.Append("\\t"); break;
                    default:
                        if (c < ' ')
                            b.Append("\\u").Append(((int)c).ToString("x4", Inv));
                        else
                            b.Append(c);
                        break;
                }
            }

            return b.ToString();
        }
    }
}
